##################################################################################
# Cloudify Script built in types and plugins definitions.
##################################################################################

plugins:
    log_shipper:
        executor: host_agent
        source: https://github.com/cloudify-cosmo/cloudify-logging-plugin/archive/1.3m7.zip
